version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    command: "start"
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      
      # Configuraciones cruciales para evitar el error de CORS con tu app React local:
      - N8N_CORS_ORIGIN=*
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
